---
#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

#MySQL Settings
mysql_root_password: "mysqlpass123"
mysql_db: "wordpress"
mysql_user: "wordpress"
mysql_password: "wordpress123"

#HTTP Settings
http_host: "ntnx.local"
http_conf: "ntnx.conf"
http_port: "80"
